PREPRINT_JOURNAL_IDS = {4306401283, 4306402567, 4306507144, 4306402450,
                        4306401687, 4306402587, 4210203035, 4306401693,
                        4306400670, 4306401696, 4306401186, 2883122597,
                        3005989158, 4306402473, 4306402219, 4306400047,
                        4306402352, 4306401713, 4210177074,
                        4306401712, 4306402614, 4306504120, 4306402488,
                        4306402105, 4306401210, 4306400573, 4306401597,
                        4393918269, 4306400194, 4306402499, 4210218052,
                        4210239046, 2764847869, 4306401228, 4306402512,
                        4306401745, 4363605331, 4306401238, 4210186582,
                        4306401879, 4306400732, 4306402530, 4210230499,
                        4306402531, 48744551, 2736351211, 4306402544,
                        4306401271, 4306401405, 4210224510}

REVIEW_JOURNAL_IDS = {206848516, 120397320, 111502347, 163102221, 316438,
                      101036573, 70620193, 160464432, 12874817, 4210178125,
                      169446993, 62674001, 7783507, 26843219, 157499488,
                      112662651, 186543748, 67216020, 2898133657, 129217179,
                      172508320, 201273009, 81141427, 96726197, 157921468,
                      183292605, 19775678, 92651206, 28635856, 116269268,
                      41981144, 18618073, 8553189, 37062379, 156364528,
                      78310130, 51877618, 2491932416, 88857351, 10734860,
                      2764917516, 93373720, 4210174246, 114927911, 4210234670,
                      83493678, 22232893, 90458436, 182717252, 181418318,
                      56802129, 150570842, 10577759, 129765729, 33396077,
                      76837745, 144797041, 124600697, 4632444, 41143188,
                      4210168218, 196724125, 4210201506, 24135080, 55210418,
                      192051125, 78119372, 116952013, 161680845, 2755384784,
                      4210198484, 62841813, 38078933, 118162903, 43764696,
                      4210219483, 173474783, 105347553}

MAX_AFFILIATIONS_PER_AUTHOR = 10
MIN_CHARACTERS_PER_AFFILIATION = 5

# large orgs that will be removed from lineage
SUPER_SYSTEM_INSTITUTIONS = {
    2802694670,  # Academic Center for Education, Culture and Research
    4210123452,  # Anahuac University Network
    2800507078,  # University of Alabama System
    2802090665,  # University of Alaska System
    3132585960,  # Arizona's Public Universities
    3211005485,  # Arkansas State University System
    2799691083,  # University of Arkansas System
    4210151215,  # Auburn University System
    919953467,   # California Community Colleges System
    127339247,   # California State University System
    2803209242,  # University of California System
    174216632,   # City University of New York
    872248612,   # Claremont Colleges
    4210131357,  # Colorado State University System
    2802236040,  # University of Colorado System
    40372098,    # DeVry University
    17866349,    # Université de Toulouse
    3132770690,  # Florida College System
    2802646605,  # Kentucky Community and Technical College System
    2799601127,  # Louisiana Community and Technical College System
    107341208,   # Louisiana State University System
    4210128516,  # Maine Community College System
    2802089280,  # Maricopa County Community College District
    2801213986,  # Montana University System
    181231927,   # National University of Ireland
    4210151660,  # Nebraska State College System
    68260882,    # Nevada System of Higher Education
    4210127926,  # North Dakota University System
    2800216316,  # Oklahoma State University System
    2800918300,  # Oregon University System
    29957033,    # Pennsylvania State System of Higher Education
    2801333002,  # Purdue University System
    4210163361,  # Rajabhat University System
    2800204061,  # Southern University System
    2801649442,  # State University System of Florida
    1327163397,  # State University of New York
    3132885913,  # Taiwan Comprehensive University System
    2800756461,  # Technical College System of Georgia
    2801273398,  # Texas State University System
    4210088475,  # Texas Tech University System
    4210138650,  # Universiti Teknologi MARA System
    1289702989,  # University System of Georgia
    1317227900,  # University System of Maryland
    2800453862,  # University System of New Hampshire
    2802096936,  # University System of Ohio
    2802348453,  # University System of Taiwan
    2801365484,  # Utah System of Higher Education
    2802841742,  # University of Massachusetts System
    2802450327,  # University of Nebraska System
    4210158053,  # University of North Carolina System
    2802090120,  # University of North Texas System
    1331384533,  # University of Hawaii System
    2801525821,  # University of Houston System
    1304256225,  # University of Wisconsin System
    2799495847,  # University of Tennessee System
    2887101046,  # University of South Carolina System
    2800421839,  # Government of the United States of America
    56066814,    # Virginia Community College System
    16452829,    # The University of Texas System
    2801919071,  # University of Illinois System
    2800403580,  # University of Minnesota System
    173268674,   # Texas A&M University System
    4390039267,  # Tokai National Higher Education and Research System
    4777552,     # University of Missouri System
}

BAD_TITLES = ['INDEX TO ADVERTISERS',
              'Questions and Answers',
              'Business and Personal',
              'LIST OF ILLUSTRATIONS',
              'high_reported_cases_plot.png',
              'Peer review statement',
              'Note by the Secretariat',
              'Data for EMSL Project 51126 from September 2020',
              'Editorial Board/Aims and Scope',
              'Preliminary material',
              'Data for EMSL Project 51127 from August 2021',
              'Verein deutscher Chemiker',
              '"Births, Marriages, and Deaths."',
              'Data for EMSL Project 60066 from August 2022',
              'Data for EMSL Project 51127 from August 2020',
              'Autorinnen und Autoren',
              'Editorial Introduction',
              'cases_by_infection.tab',
              'Nominations and Elections',
              'Instructions for Authors',
              'NOTICES OF RECENT PUBLICATIONS',
              'Notices to correspondents',
              'OUP accepted manuscript',
              'List of Abbreviations',
              'Editorial Board/Publication Information',
              'Papers to appear in forthcoming issues',
              'Taxonomic Abstract for the families.',
              'INSTRUCTIONS TO AUTHORS',
              'Publications Received',
              'Information for Contributors',
              'Data for EMSL Project 51287 from September 2022',
              'Abstracts from Current Literature',
              'Data for EMSL Project 51287 from May 2020',
              'Forthcoming meetings',
              'Data for EMSL Project 51127 from February 2022',
              'Editorials and Medical Intelligence',
              'Data for EMSL Project 51126 from January 2021',
              '[Publisher\'s information]',
              'Data for EMSL Project 60255 from July 2022',
              'Index to advertisers',
              'This Week in Science',
              '[NO TITLE AVAILABLE]',
              'Editorial Advisory Board',
              'General Introduction',
              'IFC - Editorial Board',
              'Preface to the First Edition',
              'University and Educational Intelligence',
              'Massachusetts Medical Society',
              'NOTES ON CONTRIBUTORS',
              'Letters to the Editor',
              'Letters to the editor',
              'Natural history specimens collected and/or identified and deposited.',
              'Graphical abstract TOC',
              'MEDICAL SOCIETY OF LONDON.',
              'Data for EMSL Project 50717 from January 2020',
              'Data for EMSL Project 51127 from July 2021',
              'Letter from the Editor',
              'Data for EMSL Project 51127 from November 2021',
              'Data for EMSL Project 51467 from July 2021',
              'Data for EMSL Project 51127 from July 2020',
              'Preface and Acknowledgements',
              'Data for EMSL Project 51127 from August 2022',
              'Data for EMSL Project 51287 from May 2023',
              'Data for EMSL Project 51127 from September 2021',
              'Meet Our Editorial Board Member',
              'Inside Front Cover - Editorial Board',
              'All PDFs of this category',
              'Data for EMSL Project 51127 from March 2021',
              'Data for EMSL Project 51287 from February 2023',
              'LETTERS TO THE EDITOR',
              'Contributors to this Issue',
              'Data for EMSL Project 51127 from May 2022',
              '"Letters, Notes, and Answers"',
              'Zusammenfassung und Ausblick',
              'Editorial introductions',
              'Partial Page Advertisements',
              '"Notes, Short Comments, and Answers to Correspondents."',
              'Data for EMSL Project 51287 from April 2022',
              'Data for EMSL Project 51241 from December 2022',
              'Guidelines for Authors',
              'Data for EMSL Project 51240 from October 2022',
              'Reviews and Notices of Books.',
              'Editorial: Software survey section',
              'Contributors to This Issue',
              'Data for EMSL Project 48784 from December 2019',
              'Data for EMSL Project 49510 from April 2021',
              'Data for EMSL Project 51287 from March 2023',
              'Issue Editorial Masthead',
              'Editors\' Introduction',
              'Data for EMSL Project 51287 from January 2021',
              'Data for EMSL Project 51127 from December 2021',
              'Data for EMSL Project 51287 from May 2022',
              'Queries and Minor Notes',
              'Data for EMSL Project 51287 from August 2022',
              'Data for EMSL Project 51287 from January 2022',
              'List of Contributors',
              'Data for EMSL Project 50717 from August 2020',
              'Abbildungsverzeichnis',
              'List of participants',
              'Data for EMSL Project 50686 from July 2021',
              'Data for EMSL Project 51127 from June 2020',
              'Abstracts of Current Literature',
              'Current World Literature',
              'Notes on the Contributors',
              'Other Books Received',
              'Editors’ Introduction',
              'News and Announcements',
              'Data for EMSL Project 51127 from September 2020',
              'Graphical contents list',
              'Data for EMSL Project 51287 from July 2023',
              'Instructions to authors',
              'Data for EMSL Project 60240 from April 2022',
              'Summary and Conclusions',
              'Data for EMSL Project 51127 from July 2022',
              'Data for EMSL Project 51287 from March 2022',
              'Forthcoming Articles',
              'Parliamentary Intelligence.',
              'Illustration Credits',
              'Data for EMSL Project 51287 from October 2022',
              'Introduction and Overview',
              'Data for EMSL Project 51287 from April 2020',
              'Data for EMSL Project 51127 from May 2020',
              'What Is Your Diagnosis?',
              'Data for EMSL Project 51287 from September 2021',
              'Data for EMSL Project 51287 from May 2021',
              'Data for EMSL Project 51287 from June 2023',
              'Issue Publication Information',
              'Current Publications Received',
              'Taxonomic Abstract for the genera.',
              'Preface to the Second Edition',
              'SELECTED BIBLIOGRAPHY',
              'List of Illustrations',
              '[Front cover and table of contents]',
              'Data for EMSL Project 51127 from October 2021',
              'Data for EMSL Project 51127 from February 2020',
              'Data for EMSL Project 51127 from June 2022',
              'Data for EMSL Project 60242 from August 2022',
              'Classified Advertising',
              'PUBLICATIONS RECEIVED',
              'List of figures and tables',
              'LETTER TO THE EDITOR',
              'Contributors to this issue',
              'University and Educational News',
              'List of abbreviations',
              'About the Contributors',
              'Instructions to Authors',
              'Data for EMSL Project 51240 from April 2021',
              'Abkürzungsverzeichnis',
              'Data for EMSL Project 51127 from March 2020',
              'Data for EMSL Project 51287 from April 2023',
              'Forthcoming articles',
              'Data for EMSL Project 49499 from April 2021',
              'Data for EMSL Project 51241 from May 2021',
              'Medical Notes in Parliament',
              'Matière préliminaire',
              'Recently Patented Inventions',
              'Editorial advisory board',
              'Information for Readers',
              'List of illustrations',
              'ProteomeXchange dataset',
              'Data for EMSL Project 51130 from August 2021',
              '"Letters, Notes, and Answers to Correspondents"',
              'Literaturverzeichnis',
              'Data for EMSL Project 51287 from July 2022',
              'Taxonomic Abstract for the species.',
              'Selected Bibliography',
              'Issue Information ‐ TOC',
              'Index to Advertisers',
              'Data for EMSL Project 51287 from June 2022',
              'Advertisement/Classifieds',
              'Current Medical Literature',
              'Publisher\'s Information',
              'Data for EMSL Project 51287 from December 2022',
              'Problems and Solutions',
              'Stichwortverzeichnis',
              'List of Figures and Tables',
              'Notices to Correspondents',
              'Information for readers',
              'Data for EMSL Project 51287 from January 2023',
              'Online Labour Index: Measuring the Online Gig Economy for Policy and Research',
              'Editor’s Introduction',
              'Authors of quotations wanted',
              'Letter to the Editor',
              '"Births, Marriages, and Deaths"',
              'Data for EMSL Project 51287 from November 2021',
              'Data for EMSL Project 60066 from September 2022',
              'EMPLOYMENT INFORMATION',
              'Data for EMSL Project 51287 from February 2020',
              'Title Page / Table of Contents',
              'Data for EMSL Project 51132 from March 2022',
              'Data for EMSL Project 51287 from March 2020',
              'Data for EMSL Project 51127 from October 2022',
              'Front & Back Matter',
              'Medical Appointments: Important Notice',
              'Data for EMSL Project 51127 from March 2022',
              'IFC (Editorial Board)',
              'Data for EMSL Project 47643 from January 2020',
              'Data for EMSL Project 51127 from June 2021',
              'Our Astronomical Column',
              'Preface and Acknowledgments',
              'Data for EMSL Project 60066 from June 2022',
              'Editor\'s Introduction',
              'Data for EMSL Project 50717 from September 2019',
              'Scientific Notes and News',
              'Organizing Committee',
              'Medical Appointments',
              'Publications received',
              'Letter to the editor',
              'Notes for Contributors',
              'Reports and other Publications',
              'Data for EMSL Project 51127 from January 2021',
              'Data for EMSL Project 51287 from August 2021',
              '"Syrie, Jebel Sem\'an, Barad"',
              'Data for EMSL Project 51240 from August 2022',
              '"Pflegewissenschaft, Hungen"',
              'Data for EMSL Project 51127 from November 2020',
              'Information for Authors',
              'Data for EMSL Project 60066 from January 2023',
              'British Medical Journal',
              'Verhandlungen Ärztlicher Gesellschaften',
              'Peer review declaration',
              'Data for EMSL Project 51287 from July 2021',
              'Notes on contributors',
              'Medical Diary for the ensuing Week.',
              'Data for EMSL Project 51287 from December 2021',
              'Data for EMSL Project 51127 from October 2020',
              'Reports of Societies',
              'Data for EMSL Project 51287 from December 2020',
              'Introduction générale',
              'Data for EMSL Project 51241 from September 2021',
              'Societies and Academies',
              'List of contributors',
              'Special Correspondence',
              'Peer Review Statement',
              'Titelei/Inhaltsverzeichnis',
              'Information for authors',
              'Data for EMSL Project 51287 from October 2021',
              'Data for EMSL Project 51241 from October 2021',
              'GBIF Occurrence Download',
              'Data for EMSL Project 51127 from April 2020',
              'Data for EMSL Project 51287 from November 2022',
              'Data for EMSL Project 51241 from October 2022',
              'Inside front cover (Editorial Board)',
              'Data for EMSL Project 51287 from June 2021',
              'Quellen- und Literaturverzeichnis',
              'Introducing IEEE Collabratec',
              'Data for EMSL Project 60214 from April 2023',
              'Books and Pamphlets Received',
              'Editorial Board Page',
              'Personal‐ und Hochschulnachrichten',
              'Data for EMSL Project 51287 from July 2020',
              'Public Health and Poor-Law Medical Services',
              'Data for EMSL Project 51127 from December 2020',
              'Data for EMSL Project 51287 from April 2021',
              'Data for EMSL Project 51127 from January 2020',
              'Preliminary Material',
              'Notes on Contributors']

ROR_COUNTRIES_LIST = [('ad', 'andorra'),
 ('ae', 'al imarat al arabiyah al muttahidah'),
 ('ae', 'arab emirates'),
 ('ae', 'uae'),
 ('ae', 'united arab emirates'),
 ('af', 'afghanestan'),
 ('af', 'afghanistan'),
 ('ag', 'antigua'),
 ('ag', 'antigua and barbuda'),
 ('ag', 'barbuda'),
 ('ai', 'anguilla'),
 ('al', 'albania'),
 ('al', 'shqiperia'),
 ('am', 'armenia'),
 ('am', 'hayastan'),
 ('an', 'netherlands antilles'),
 ('ao', 'angola'),
 ('aq', 'antarctica'),
 ('ar', 'ar'),
 ('ar', 'argentina'),
 ('ar', 'argentine'),
 ('as', 'american samoa'),
 ('at', 'austria'),
 ('at', 'aut'),
 ('at', 'oesterreich'),
 ('at', 'osterreich'),
 ('au', 'au'),
 ('au', 'aus'),
 ('au', 'australia'),
 ('aw', 'aruba'),
 ('ax', 'aland islands'),
 ('az', 'azarbaycan respublikasi'),
 ('az', 'aze'),
 ('az', 'azerbaijan'),
 ('ba', 'bosna i hercegovina'),
 ('ba', 'bosnia'),
 ('ba', 'bosnia and herzegovina'),
 ('ba', 'herzegovina'),
 ('bb', 'barbados'),
 ('bd', 'bangladesh'),
 ('be', 'bel'),
 ('be', 'belgie'),
 ('be', 'belgique'),
 ('be', 'belgium'),
 ('bf', 'bfa'),
 ('bf', 'burkina faso'),
 ('bg', 'bulariya'),
 ('bg', 'bulgaria'),
 ('bg', 'republika bulgariya'),
 ('bh', 'al bahrayn'),
 ('bh', 'bahrain'),
 ('bi', 'burundi'),
 ('bj', 'ben'),
 ('bj', 'benin'),
 ('bl', 'saint barthelemy'),
 ('bm', 'bermuda'),
 ('bn', 'brunei'),
 ('bn', 'brunei darussalam'),
 ('bo', 'bolivia'),
 ('bq', 'bonaire'),
 ('bq', 'bonaire, sint eustatius and saba'),
 ('br', 'br'),
 ('br', 'bra'),
 ('br', 'brasil'),
 ('br', 'brazil'),
 ('bs', 'bahamas'),
 ('bs', 'the bahamas'),
 ('bt', 'bhutan'),
 ('bt', 'drukyul'),
 ('bv', 'bouvet island'),
 ('bw', 'botswana'),
 ('by', 'belarus'),
 ('by', 'byelarus'),
 ('bz', 'belice'),
 ('bz', 'belize'),
 ('ca', 'ca'),
 ('ca', 'can'),
 ('ca', 'canada'),
 ('cc', 'cocos islands'),
 ('cc', 'keeling islands'),
 ('cf', 'central african republic'),
 ('cf', 'republique centrafricaine'),
 ('cg', 'congo'),
 ('cg', 'democratic republic of the congo'),
 ('cg', 'republic of the congo'),
 ('cg', 'republique democratique du congo'),
 ('cg', 'republique du congo'),
 ('ch', 'che'),
 ('ch', 'schweiz'),
 ('ch', 'suisse'),
 ('ch', 'svizzera'),
 ('ch', 'switzerland'),
 ('ci', "cote d'ivoire"),
 ('ck', 'cook islands'),
 ('cl', 'chile'),
 ('cm', 'cameroon'),
 ('cm', 'cameroun'),
 ('cn', 'china'),
 ('cn', "china (people's republic of)"),
 ('cn', 'chn'),
 ('cn', 'cn'),
 ('cn', "people's republic of china"),
 ('cn', 'p r china'),
 ('cn', 'p. r. china'),
 ('cn', 'pr china'),
 ('cn', 'republic of china'),
 ('cn', 'r. o. c.'),
 ('cn', 'zhong guo'),
 ('co', 'col'),
 ('co', 'colombia'),
 ('cr', 'costa rica'),
 ('cr', 'cri'),
 ('cu', 'cuba'),
 ('cv', 'cabo verde'),
 ('cv', 'cape verde'),
 ('cw', 'curacao'),
 ('cx', 'christmas island'),
 ('cy', 'cyprus'),
 ('cy', 'kibris'),
 ('cy', 'kypros'),
 ('cz', 'ceska republika'),
 ('cz', 'cze'),
 ('cz', 'czech republic'),
 ('de', 'de'),
 ('de', 'deu'),
 ('de', 'deutschland'),
 ('de', 'federal republic of germany'),
 ('de', 'germany'),
 ('dj', 'djibouti'),
 ('dk', 'danmark'),
 ('dk', 'denmark'),
 ('dk', 'dnk'),
 ('dm', 'dominica'),
 ('do', 'dominican republic'),
 ('do', 'republica dominicana'),
 ('dz', 'algeria'),
 ('dz', "al jaza'ir"),
 ('ec', 'ecuador'),
 ('ee', 'eesti'),
 ('ee', 'est'),
 ('ee', 'estonia'),
 ('eg', 'egypt'),
 ('eg', 'misr'),
 ('eh', 'western sahara'),
 ('er', 'eritrea'),
 ('er', 'ertra'),
 ('es', 'esp'),
 ('es', 'espana'),
 ('es', 'spain'),
 ('et', 'ethiopia'),
 ('et', "yeityop'iya"),
 ('eu', 'eec'),
 ('fi', 'fin'),
 ('fi', 'finland'),
 ('fi', 'suomi'),
 ('fj', 'fiji'),
 ('fk', 'falkland islands'),
 ('fm', 'federated states of micronesia'),
 ('fm', 'micronesia'),
 ('fo', 'faroe islands'),
 ('fr', 'fr'),
 ('fr', 'fra'),
 ('fr', 'france'),
 ('fr', 'republique francaise'),
 ('ga', 'gabon'),
 ('gd', 'grenada'),
 ('ge', 'georgia'),
 ('ge', "sak'art'velo"),
 ('gf', 'french guiana'),
 ('gg', 'guernsey'),
 ('gh', 'ghana'),
 ('gi', 'gibraltar'),
 ('gl', 'greenland'),
 ('gm', 'gambia'),
 ('gn', 'guinea'),
 ('gn', 'guinea ecuatorial'),
 ('gn', 'guinee'),
 ('gp', 'guadeloupe'),
 ('gq', 'equatorial guinea'),
 ('gr', 'ellas'),
 ('gr', 'grc'),
 ('gr', 'greece'),
 ('gs', 'south georgia'),
 ('gt', 'guatemala'),
 ('gu', 'guam'),
 ('gw', 'guinea-bissau'),
 ('gw', 'guine-bissau'),
 ('gy', 'guyana'),
 ('hk', 'hong kong'),
 ('hm', 'heard island'),
 ('hm', 'heard island and mcdonald islands'),
 ('hm', 'mcdonald islands'),
 ('hn', 'honduras'),
 ('hr', 'croatia'),
 ('hr', 'hrvatska'),
 ('ht', 'haiti'),
 ('hu', 'hun'),
 ('hu', 'hungary'),
 ('hu', 'magyarorszag'),
 ('id', 'idn'),
 ('id', 'indonesia'),
 ('ie', 'eire'),
 ('ie', 'ireland'),
 ('ie', 'irl'),
 ('il', 'isr'),
 ('il', 'israel'),
 ('il', "yisra'el"),
 ('im', 'isle of man'),
 ('in', 'bharat'),
 ('in', 'ind'),
 ('in', 'india'),
 ('io', 'british indian ocean territory'),
 ('iq', 'al iraq'),
 ('iq', 'iraq'),
 ('ir', 'iran'),
 ('ir', 'persia'),
 ('is', 'iceland'),
 ('is', 'isl'),
 ('is', 'island'),
 ('it', 'ita'),
 ('it', 'italia'),
 ('it', 'italy'),
 ('je', 'jersey'),
 ('jm', 'jamaica'),
 ('jo', 'al urdun'),
 ('jo', 'jordan'),
 ('jp', 'japan'),
 ('jp', 'jpn'),
 ('jp', 'nippon'),
 ('jp', 'tokyo'),
 ('ke', 'kenya'),
 ('kg', 'kyrgyz respublikasy'),
 ('kg', 'kyrgyzstan'),
 ('kh', 'cambodia'),
 ('kh', 'kampuchea'),
 ('ki', 'kiribati'),
 ('km', 'comores'),
 ('km', 'comoros'),
 ('kn', 'nevis'),
 ('kn', 'saint kitts'),
 ('kn', 'saint kitts and nevis'),
 ('ko', 'kosova'),
 ('ko', 'kosovo'),
 ('kp', 'choson'),
 ('kp', 'choson-minjujuui-inmin-konghwaguk'),
 ('kp', 'north korea'),
 ('kr', 'kor'),
 ('kr', 'korea'),
 ('kr', 'republic of korea'),
 ('kr', 'korea (republic of)'),
 ('kr', 'south korea'),
 ('kr', "taehan-min'guk"),
 ('kw', 'al kuwayt'),
 ('kw', 'kuwait'),
 ('ky', 'cayman islands'),
 ('kz', 'kazakhstan'),
 ('kz', 'qazaqstan'),
 ('la', "lao (people's democratic republic)"),
 ('la', "lao people's democratic republic"),
 ('la', 'laos'),
 ('la', 'sathalanalat paxathipatai paxaxon lao'),
 ('lb', 'lebanon'),
 ('lb', 'lubnan'),
 ('lc', 'saint lucia'),
 ('li', 'liechtenstein'),
 ('lk', 'sri lanka'),
 ('lr', 'liberia'),
 ('ls', 'lesotho'),
 ('lt', 'lietuva'),
 ('lt', 'lithuania'),
 ('lt', 'ltu'),
 ('lu', 'lux'),
 ('lu', 'luxembourg'),
 ('lv', 'latvia'),
 ('lv', 'latvija'),
 ('ly', 'libya'),
 ('ly', 'libyan arab jamahiriya'),
 ('ma', 'al maghrib'),
 ('ma', 'morocco'),
 ('mc', 'monaco'),
 ('md', 'moldova'),
 ('md', 'moldova (republic of)'),
 ('md', 'republic of moldova'),
 ('me', 'montenegro'),
 ('mf', 'saint martin'),
 ('mf', 'saint martin (french part)'),
 ('mg', 'madagascar'),
 ('mh', 'marshall islands'),
 ('mk', 'federal republic of yugoslavia'),
 ('mk', 'former yugoslav republic of macedonia'),
 ('mk', 'macedonia'),
 ('mk', 'makedonija'),
 ('mk', 'yugoslavia'),
 ('ml', 'mali'),
 ('mm', 'burma'),
 ('mm', 'myanma naingngandaw'),
 ('mm', 'myanmar'),
 ('mn', 'mongolia'),
 ('mn', 'mongol uls'),
 ('mo', 'macao'),
 ('mp', 'northern mariana islands'),
 ('mq', 'martinique'),
 ('mr', 'mauritania'),
 ('mr', 'muritaniyah'),
 ('ms', 'montserrat'),
 ('mt', 'malta'),
 ('mu', 'mauritius'),
 ('mv', 'dhivehi raajje'),
 ('mv', 'maldives'),
 ('mw', 'malawi'),
 ('mx', 'mex'),
 ('mx', 'mexico'),
 ('my', 'malaysia'),
 ('mz', 'mocambique'),
 ('mz', 'mozambique'),
 ('na', 'namibia'),
 ('nc', 'new caledonia'),
 ('ne', 'niger'),
 ('nf', 'norfolk island'),
 ('ng', 'nigeria'),
 ('ni', 'nicaragua'),
 ('nl', 'nederland'),
 ('nl', 'netherlands'),
 ('nl', 'nl'),
 ('nl', 'nld'),
 ('nl', 'the netherlands'),
 ('no', 'nor'),
 ('no', 'norge'),
 ('no', 'norway'),
 ('np', 'nepal'),
 ('nr', 'nauru'),
 ('nu', 'niue'),
 ('nz', 'new zealand'),
 ('nz', 'nzl'),
 ('om', 'oman'),
 ('om', 'uman'),
 ('pa', 'pan'),
 ('pa', 'panama'),
 ('pe', 'peru'),
 ('pf', 'french polynesia'),
 ('pf', 'pyf'),
 ('pg', 'papua new guinea'),
 ('ph', 'philippines'),
 ('ph', 'pilipinas'),
 ('pk', 'pakistan'),
 ('pl', 'pol'),
 ('pl', 'poland'),
 ('pl', 'polska'),
 ('pm', 'miquelon'),
 ('pm', 'saint pierre'),
 ('pm', 'saint pierre and miquelon'),
 ('pn', 'pitcairn'),
 ('pr', 'puerto rico'),
 ('ps', 'palestine'),
 ('pt', 'portugal'),
 ('pw', 'palau'),
 ('py', 'paraguay'),
 ('qa', 'qatar'),
 ('re', 'reunion'),
 ('ro', 'romania'),
 ('ro', 'rou'),
 ('rs', 'serbia'),
 ('rs', 'srbija-crna gora'),
 ('ru', 'rossiya'),
 ('ru', 'rus'),
 ('ru', 'russia'),
 ('ru', 'russian federation'),
 ('rw', 'rwanda'),
 ('sa', 'al arabiyah as suudiyah'),
 ('sa', 'saudi arabia'),
 ('sb', 'solomon islands'),
 ('sc', 'seychelles'),
 ('sd', 'as-sudan'),
 ('sd', 'sudan'),
 ('se', 'sverige'),
 ('se', 'swe'),
 ('se', 'sweden'),
 ('sg', 'sgp'),
 ('sg', 'singapore'),
 ('sh', 'saint helena'),
 ('si', 'slovenia'),
 ('si', 'slovenija'),
 ('si', 'svn'),
 ('sj', 'jan mayen'),
 ('sj', 'svalbard'),
 ('sk', 'slovakia'),
 ('sk', 'slovensko'),
 ('sk', 'svk'),
 ('sl', 'sierra leone'),
 ('sm', 'san marino'),
 ('sn', 'sen'),
 ('sn', 'senegal'),
 ('so', 'somalia'),
 ('sr', 'suriname'),
 ('ss', 'south sudan'),
 ('st', 'principe'),
 ('st', 'sao tome'),
 ('st', 'sao tome and principe'),
 ('st', 'sao tome e principe'),
 ('sv', 'el salvador'),
 ('sv', 'slv'),
 ('sx', 'sint maarten'),
 ('sy', 'suriyah'),
 ('sy', 'syria'),
 ('sy', 'syrian arab republic'),
 ('sz', 'swaziland'),
 ('tc', 'caicos islands'),
 ('tc', 'turks'),
 ('tc', 'turks and caicos islands'),
 ('td', 'chad'),
 ('td', 'tchad'),
 ('tf', 'french southern territories'),
 ('tg', 'togo'),
 ('th', 'muang thai'),
 ('th', 'thailand'),
 ('tj', 'jumhurii tojikistan'),
 ('tj', 'tajikistan'),
 ('tk', 'tokelau'),
 ('tl', 'timor-leste'),
 ('tm', 'turkmenistan'),
 ('tn', 'tunisia'),
 ('to', 'tonga'),
 ('tr', 'tur'),
 ('tr', 'turkey'),
 ('tr', 'turkiye'),
 ('tt', 'tobago'),
 ('tt', 'trinidad'),
 ('tt', 'trinidad and tobago'),
 ('tv', 'tuvalu'),
 ('tw', 'taiwan'),
 ('tw', "t'ai-wan"),
 ('tw', 'taiwan r.o.c'),
 ('tw', 'twn'),
 ('tz', 'tanzania'),
 ('tz', 'tanzania (united republic of)'),
 ('ua', 'ukr'),
 ('ua', 'ukraine'),
 ('ua', 'ukrayina'),
 ('ug', 'uganda'),
 ('uk', 'gb'),
 ('uk', 'gbr'),
 ('uk', 'great britain'),
 ('uk', 'northern ireland'),
 ('uk', 'london'),
 ('uk', 'scotland'),
 ('uk', 'uk'),
 ('uk', 'u. k.'),
 ('uk', 'u.k.'),
 ('uk', 'u. k'),
 ('uk', 'u.k'),
 ('uk', 'united kingdom'),
 ('um', 'united states minor outlying islands'),
 ('us', 'ak'),
 ('us', 'al'),
 ('us', 'alabama'),
 ('us', 'alaska'),
 ('us', 'ar'),
 ('us', 'arizona'),
 ('us', 'arkansas'),
 ('us', 'az'),
 ('us', 'ca'),
 ('us', 'california'),
 ('us', 'co'),
 ('us', 'colorado'),
 ('us', 'connecticut'),
 ('us', 'ct'),
 ('us', 'de'),
 ('us', 'delaware'),
 ('us', 'fl'),
 ('us', 'florida'),
 ('us', 'ga'),
 ('us', 'georgia'),
 ('us', 'hawaii'),
 ('us', 'hi'),
 ('us', 'ia'),
 ('us', 'id'),
 ('us', 'idaho'),
 ('us', 'il'),
 ('us', 'ill'),
 ('us', 'illinois'),
 ('us', 'in'),
 ('us', 'indiana'),
 ('us', 'iowa'),
 ('us', 'kansas'),
 ('us', 'kentucky'),
 ('us', 'ks'),
 ('us', 'ky'),
 ('us', 'la'),
 ('us', 'louisiana'),
 ('us', 'ma'),
 ('us', 'maine'),
 ('us', 'maryland'),
 ('us', 'massachusetts'),
 ('us', 'me'),
 ('us', 'mi'),
 ('us', 'michigan'),
 ('us', 'minnesota'),
 ('us', 'mississippi'),
 ('us', 'missouri'),
 ('us', 'mn'),
 ('us', 'mo'),
 ('us', 'montana'),
 ('us', 'ms'),
 ('us', 'mt'),
 ('us', 'nc'),
 ('us', 'nd'),
 ('us', 'ne'),
 ('us', 'nebraska'),
 ('us', 'nevada'),
 ('us', 'new hampshire'),
 ('us', 'new jersey'),
 ('us', 'new mexico'),
 ('us', 'new york'),
 ('us', 'nh'),
 ('us', 'nj'),
 ('us', 'nm'),
 ('us', 'north carolina'),
 ('us', 'north dakota'),
 ('us', 'nv'),
 ('us', 'ny'),
 ('us', 'oh'),
 ('us', 'ohio'),
 ('us', 'ok'),
 ('us', 'okla'),
 ('us', 'oklahoma'),
 ('us', 'or'),
 ('us', 'oregon'),
 ('us', 'pa'),
 ('us', 'pennsylvania'),
 ('us', 'rhode island'),
 ('us', 'ri'),
 ('us', 'sc'),
 ('us', 'sd'),
 ('us', 'south carolina'),
 ('us', 'south dakota'),
 ('us', 'tennessee'),
 ('us', 'texas'),
 ('us', 'tn'),
 ('us', 'tx'),
 ('us', 'united states'),
 ('us', 'united states of america'),
 ('us', 'us'),
 ('us', 'u. s.'),
 ('us', 'u.s.'),
 ('us', 'u. s'),
 ('us', 'u.s'),
 ('us', 'usa'),
 ('us', 'u. s. a.'),
 ('us', 'u.s.a.'),
 ('us', 'ut'),
 ('us', 'utah'),
 ('us', 'va'),
 ('us', 'vermont'),
 ('us', 'virginia'),
 ('us', 'vt'),
 ('us', 'wa'),
 ('us', 'washington'),
 ('us', 'west virginia'),
 ('us', 'wi'),
 ('us', 'wisconsin'),
 ('us', 'wv'),
 ('us', 'wy'),
 ('us', 'wyoming'),
 ('uy', 'uruguay'),
 ('uz', 'uzbekistan'),
 ('uz', 'uzbekiston respublikasi'),
 ('va', 'citta del vaticano'),
 ('va', 'holy see'),
 ('va', 'santa sede'),
 ('va', 'vatican'),
 ('va', 'vatican city'),
 ('vc', 'saint vincent'),
 ('vc', 'saint vincent and the grenadines'),
 ('vc', 'the grenadines'),
 ('ve', 'venezuela'),
 ('vg', 'virgin islands'),
 ('vn', 'vietnam'),
 ('vn', 'viet nam'),
 ('vu', 'vanuatu'),
 ('wf', 'futuna'),
 ('wf', 'wallis'),
 ('wf', 'wallis and futuna'),
 ('ws', 'samoa'),
 ('ye', 'al yaman'),
 ('ye', 'yemen'),
 ('yt', 'mayotte'),
 ('za', 'south africa'),
 ('za', 'zaf'),
 ('zm', 'zambia'),
 ('zw', 'zimbabwe')]
